-- UploadNPlay achievements + per-game API credentials
-- Run after schema.sql.

create extension if not exists pgcrypto;

create table if not exists public.game_achievements (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references public.games(id) on delete cascade,
  achievement_key text not null,
  name text not null,
  description text not null default '',
  icon_url text,
  points integer not null default 10 check (points >= 0 and points <= 10000),
  secret boolean not null default false,
  client_unlockable boolean not null default true,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (game_id, achievement_key)
);

create table if not exists public.game_achievement_unlocks (
  id bigint generated by default as identity primary key,
  achievement_id uuid not null references public.game_achievements(id) on delete cascade,
  game_id uuid not null references public.games(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  unique (achievement_id, user_id)
);

create table if not exists public.game_api_credentials (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null unique references public.games(id) on delete cascade,
  public_key text not null unique,
  secret_hash text not null,
  secret_last4 text not null,
  created_at timestamptz not null default now(),
  rotated_at timestamptz not null default now()
);

create index if not exists game_achievements_game_idx on public.game_achievements(game_id);
create index if not exists game_achievements_enabled_idx on public.game_achievements(game_id, enabled);
create index if not exists achievement_unlocks_game_idx on public.game_achievement_unlocks(game_id);
create index if not exists achievement_unlocks_user_idx on public.game_achievement_unlocks(user_id);

create or replace function public.set_achievement_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists game_achievement_set_updated_at on public.game_achievements;
create trigger game_achievement_set_updated_at
before update on public.game_achievements
for each row execute procedure public.set_achievement_updated_at();

create or replace function public.game_owner_or_admin(target_game uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.games g
    where g.id = target_game
      and (g.developer_id = auth.uid() or public.is_admin())
  );
$$;

grant execute on function public.game_owner_or_admin(uuid) to authenticated;

grant select on public.game_achievements to anon, authenticated;
grant insert, update, delete on public.game_achievements to authenticated;
grant select, insert on public.game_achievement_unlocks to authenticated;
grant select on public.game_api_credentials to authenticated;

alter table public.game_achievements enable row level security;
alter table public.game_achievement_unlocks enable row level security;
alter table public.game_api_credentials enable row level security;

drop policy if exists "Public can read enabled achievements" on public.game_achievements;
drop policy if exists "Developers can create achievements" on public.game_achievements;
drop policy if exists "Developers can update achievements" on public.game_achievements;
drop policy if exists "Developers can delete achievements" on public.game_achievements;

drop policy if exists "Players can read own achievement unlocks" on public.game_achievement_unlocks;
drop policy if exists "Developers can read achievement unlocks" on public.game_achievement_unlocks;
drop policy if exists "Players can create own achievement unlocks" on public.game_achievement_unlocks;

drop policy if exists "Developers can read API credential metadata" on public.game_api_credentials;

create policy "Public can read enabled achievements"
on public.game_achievements for select
to anon, authenticated
using (
  (enabled = true
    and exists (select 1 from public.games g where g.id = game_id and g.status = 'approved'))
  or public.game_owner_or_admin(game_id)
);

create policy "Developers can create achievements"
on public.game_achievements for insert
to authenticated
with check (public.game_owner_or_admin(game_id));

create policy "Developers can update achievements"
on public.game_achievements for update
to authenticated
using (public.game_owner_or_admin(game_id))
with check (public.game_owner_or_admin(game_id));

create policy "Developers can delete achievements"
on public.game_achievements for delete
to authenticated
using (public.game_owner_or_admin(game_id));

create policy "Players can read own achievement unlocks"
on public.game_achievement_unlocks for select
to authenticated
using (auth.uid() = user_id);

create policy "Developers can read achievement unlocks"
on public.game_achievement_unlocks for select
to authenticated
using (public.game_owner_or_admin(game_id));

create policy "Players can create own achievement unlocks"
on public.game_achievement_unlocks for insert
to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.game_achievements a
    where a.id = achievement_id
      and a.game_id = game_achievement_unlocks.game_id
      and a.enabled = true
      and a.client_unlockable = true
  )
);

create policy "Developers can read API credential metadata"
on public.game_api_credentials for select
to authenticated
using (public.game_owner_or_admin(game_id));

create or replace function public.rotate_game_api_secret(target_game uuid)
returns json
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  new_public_key text;
  new_secret text;
begin
  if not public.game_owner_or_admin(target_game) then
    raise exception 'not authorized';
  end if;

  new_public_key := 'unp_' || encode(gen_random_bytes(12), 'hex');
  new_secret := encode(gen_random_bytes(32), 'hex');

  insert into public.game_api_credentials(game_id, public_key, secret_hash, secret_last4, rotated_at)
  values (
    target_game,
    new_public_key,
    encode(digest(new_secret, 'sha256'), 'hex'),
    right(new_secret, 4),
    now()
  )
  on conflict (game_id) do update
    set public_key = excluded.public_key,
        secret_hash = excluded.secret_hash,
        secret_last4 = excluded.secret_last4,
        rotated_at = now();

  return json_build_object(
    'publicKey', new_public_key,
    'secret', new_secret,
    'warning', 'Store this server secret securely. It is not stored in readable form and cannot be shown again.'
  );
end;
$$;

grant execute on function public.rotate_game_api_secret(uuid) to authenticated;

create or replace function public.verify_game_api_secret(target_game uuid, provided_secret text)
returns boolean
language sql
stable
security definer
set search_path = public, extensions
as $$
  select exists (
    select 1
    from public.game_api_credentials c
    where c.game_id = target_game
      and c.secret_hash = encode(digest(provided_secret, 'sha256'), 'hex')
  );
$$;

grant execute on function public.verify_game_api_secret(uuid, text) to anon, authenticated;

grant usage, select on sequence public.game_achievement_unlocks_id_seq to authenticated;
