-- UploadNPlay game-scoped launch tokens
-- Run after schema.sql and achievements.sql.

create extension if not exists pgcrypto;

create table if not exists public.game_launch_tokens (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists game_launch_tokens_game_idx on public.game_launch_tokens(game_id);
create index if not exists game_launch_tokens_expires_idx on public.game_launch_tokens(expires_at);

alter table public.game_launch_tokens enable row level security;

grant execute on function public.create_game_launch_token(uuid) to authenticated;
grant execute on function public.resolve_game_launch_token(uuid, text) to anon, authenticated;

drop policy if exists "No direct access to launch tokens" on public.game_launch_tokens;
create policy "No direct access to launch tokens"
on public.game_launch_tokens for select
to authenticated
using (false);

create or replace function public.create_game_launch_token(target_game uuid)
returns json
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  raw_token text;
  token_expires timestamptz;
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;

  if not exists (
    select 1 from public.games g
    where g.id = target_game
      and g.status = 'approved'
  ) then
    raise exception 'game is not approved';
  end if;

  raw_token := 'unpt_' || encode(gen_random_bytes(32), 'hex');
  token_expires := now() + interval '30 minutes';

  insert into public.game_launch_tokens(game_id, user_id, token_hash, expires_at)
  values (
    target_game,
    auth.uid(),
    encode(digest(raw_token, 'sha256'), 'hex'),
    token_expires
  );

  return json_build_object(
    'token', raw_token,
    'expiresAt', token_expires
  );
end;
$$;

drop function if exists public.resolve_game_launch_token(uuid, text);
create or replace function public.resolve_game_launch_token(target_game uuid, provided_token text)
returns uuid
language sql
stable
security definer
set search_path = public, extensions
as $$
  select t.user_id
  from public.game_launch_tokens t
  where t.game_id = target_game
    and t.token_hash = encode(digest(provided_token, 'sha256'), 'hex')
    and t.expires_at > now()
  limit 1;
$$;

-- Keep expired one-time credentials from accumulating.
create or replace function public.cleanup_expired_game_launch_tokens()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare removed integer;
begin
  delete from public.game_launch_tokens where expires_at <= now();
  get diagnostics removed = row_count;
  return removed;
end;
$$;
