-- UploadNPlay database setup
-- Run this once in the Supabase SQL Editor.
-- Safe to run again: existing tables/policies are updated instead of duplicated.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  display_name text,
  bio text not null default '',
  avatar_url text,
  is_dev boolean not null default false,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists display_name text;
alter table public.profiles add column if not exists bio text not null default '';
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists is_dev boolean not null default false;
alter table public.profiles add column if not exists is_admin boolean not null default false;

create table if not exists public.games (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null default '',
  developer_id uuid not null references public.profiles(id) on delete cascade,
  zip_path text not null default '',
  entry_point text not null default 'index.html',
  thumbnail_url text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.games add column if not exists status text not null default 'pending';
alter table public.games add column if not exists rejection_reason text;
alter table public.games add column if not exists updated_at timestamptz not null default now();

create table if not exists public.game_views (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  viewer_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists games_status_idx on public.games(status);
create index if not exists games_developer_idx on public.games(developer_id);
create index if not exists games_created_idx on public.games(created_at desc);
create index if not exists game_views_game_idx on public.game_views(game_id);
create index if not exists game_views_created_idx on public.game_views(created_at desc);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and is_admin = true
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  base_username text;
begin
  base_username := lower(regexp_replace(
    coalesce(new.raw_user_meta_data->>'user_name', split_part(coalesce(new.email,'player'),'@',1)),
    '[^a-zA-Z0-9_]', '', 'g'
  ));
  if base_username = '' then base_username := 'player'; end if;
  insert into public.profiles (id, username, display_name)
  values (new.id, left(base_username, 30), left(coalesce(new.raw_user_meta_data->>'display_name', base_username), 80))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.set_games_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists games_set_updated_at on public.games;
create trigger games_set_updated_at
before update on public.games
for each row execute procedure public.set_games_updated_at();

-- Explicit table privileges are required in addition to RLS policies for the
-- Supabase REST API roles used by the frontend.
grant usage on schema public to anon, authenticated;
grant select on public.profiles to anon, authenticated;
grant insert, update on public.profiles to authenticated;
grant select on public.games to anon, authenticated;
grant insert, update, delete on public.games to authenticated;
grant select, insert on public.game_views to anon, authenticated;

grant execute on function public.is_admin() to anon, authenticated;

a-- Enable row level security.
alter table public.profiles enable row level security;
alter table public.games enable row level security;
alter table public.game_views enable row level security;

-- Remove old/duplicate policies so this script can safely be rerun.
drop policy if exists "Public profiles are readable" on public.profiles;
drop policy if exists "Profiles are publicly readable" on public.profiles;
drop policy if exists "Users can create their own profile" on public.profiles;
drop policy if exists "Users can update their own profile" on public.profiles;

drop policy if exists "Public games are readable" on public.games;
drop policy if exists "Games are publicly readable" on public.games;
drop policy if exists "Approved games are public" on public.games;
drop policy if exists "Authenticated users can publish games" on public.games;
drop policy if exists "Authenticated users can submit games" on public.games;
drop policy if exists "Developers can update their games" on public.games;
drop policy if exists "Developers can update their pending games" on public.games;
drop policy if exists "Developers can delete their games" on public.games;

drop policy if exists "Anyone can record game views" on public.game_views;
drop policy if exists "Developers can read their game views" on public.game_views;
drop policy if exists "Admins can read all game views" on public.game_views;

create policy "Profiles are publicly readable"
on public.profiles for select
to anon, authenticated
using (true);

create policy "Users can create their own profile"
on public.profiles for insert
to authenticated
with check (auth.uid() = id);

create policy "Users can update their own profile"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (
  auth.uid() = id
  and is_dev = (select p.is_dev from public.profiles p where p.id = auth.uid())
  and is_admin = (select p.is_admin from public.profiles p where p.id = auth.uid())
);

create policy "Approved games are public"
on public.games for select
to anon, authenticated
using (status = 'approved' or auth.uid() = developer_id or public.is_admin());

create policy "Authenticated users can submit games"
on public.games for insert
to authenticated
with check (auth.uid() = developer_id);

create policy "Developers can update their games"
on public.games for update
to authenticated
using (auth.uid() = developer_id or public.is_admin())
with check (auth.uid() = developer_id or public.is_admin());

create policy "Developers can delete their games"
on public.games for delete
to authenticated
using (auth.uid() = developer_id or public.is_admin());

create policy "Anyone can record game views"
on public.game_views for insert
to anon, authenticated
with check (true);

create policy "Developers can read their game views"
on public.game_views for select
to authenticated
using (
  exists (
    select 1 from public.games g
    where g.id = game_id and g.developer_id = auth.uid()
  )
  or public.is_admin()
);

-- New accounts automatically receive a profile.
-- IMPORTANT: keep is_admin false by default. After your account exists, make
-- your account the owner/admin from the SQL editor, for example:
-- update public.profiles set is_dev = true, is_admin = true where username = 'yourusername';
