create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, username text unique not null, created_at timestamptz not null default now());
create table if not exists public.games (id uuid primary key default gen_random_uuid(), title text not null, description text not null default '', developer_id uuid not null references public.profiles(id) on delete cascade, zip_path text not null default '', entry_point text not null default 'index.html', thumbnail_url text, created_at timestamptz not null default now());
alter table public.profiles enable row level security;
alter table public.games enable row level security;
create policy "Public profiles are readable" on public.profiles for select using (true);
create policy "Users can create their own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update their own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "Public games are readable" on public.games for select using (true);
create policy "Authenticated users can publish games" on public.games for insert to authenticated with check (auth.uid() = developer_id);
create policy "Developers can update their games" on public.games for update to authenticated using (auth.uid() = developer_id) with check (auth.uid() = developer_id);
create policy "Developers can delete their games" on public.games for delete to authenticated using (auth.uid() = developer_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (id, username) values (new.id, coalesce(new.raw_user_meta_data->>'user_name', split_part(coalesce(new.email,'player'), '@', 1))) on conflict (id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
